//空岛特供
ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu
    gtr.assembler('disksavior:ulv_fragment_world_collection_machine')
        .circuit(30)
        .itemInputs('2x gtceu:lead_single_cable', '2x gtceu:rubber_log', 'gtlcore:treasures_crystal', 'gtceu:lv_machine_hull', 'gtlcore:mining_crystal', '2x minecraft:anvil')
        .itemOutputs('gtceu:ulv_fragment_world_collection_machine')
        .EUt(GTValues.VA[GTValues.ULV])
        .duration(200)
    gtr.assembler('disksavior:large_fragment_world_collection_machine')
        .circuit(30)
        .itemInputs('2x #gtceu:circuits/iv', '2x gtceu:ev_field_generator', '2x gtceu:tungstensteel_gearbox', 'gtlcore:treasures_crystal', 'gtceu:ulv_fragment_world_collection_machine', 'gtlcore:mining_crystal')
        .itemOutputs('gtceu:large_fragment_world_collection_machine')
        .EUt(GTValues.VA[GTValues.EV])
        .duration(200)
    //三碎片化反
    gtr.large_chemical_reactor('disksavior:crystal')
        .circuit(1)
        .notConsumable('2147483647x gtceu:ulv_fragment_world_collection_machine')
        .notConsumable('2147483647x gtceu:large_fragment_world_collection_machine')
        .inputFluids('gtceu:steam 1')
        .chancedOutput("gtlcore:mining_crystal", 5, 0)
        .chancedOutput("gtlcore:treasures_crystal", 3, 0)
        .chancedOutput("gtlcore:miracle_crystal", 1, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(200)
    //宏原子版
    gtr.large_chemical_reactor('disksavior:crystal_max')
        .circuit(2)
        .notConsumable('2147483647x gtceu:ulv_fragment_world_collection_machine')
        .notConsumable('2147483647x gtceu:large_fragment_world_collection_machine')
        .notConsumable('1024x gtladditions:macro_atomic_resonant_fragment_stripper')
        .inputFluids('gtceu:steam 1')
        .chancedOutput("gtlcore:mining_crystal", 5, 0)
        .chancedOutput("gtlcore:treasures_crystal", 3, 0)
        .chancedOutput("gtlcore:miracle_crystal", 1, 0)
        .EUt(GTValues.VA[GTValues.ULV])
        .duration(200)
})